### ISSUE TITLE
home > on load hero panel loads late so bottom featues get pushed down.

### ISSUE THREAD

**Issue by kurumi0909** [kurumi0909/kocostar#25]
When you load the home page, the bottom features are on top and get pushed down as the hero appears.
is there a way to fix this? maybe keep the hero area blank when it loads so that you don't see a weird push down motion?

**Comment by skinall13** [comment]
Done. 
Please find the link below

http://dev.sitessimply.com/html/kacostar/

**Comment by kurumi0909** [comment]
hm it's still happening for me? for a blink of a sec, i see 'glowing youthful skin' panel on the top and it gets pushed down.

**Comment by skinall13** [comment]
Done. 
Please find the link below

http://dev.sitessimply.com/html/kacostar/

**Comment by kurumi0909** [comment]
thank you so much! lastly can you make the loading icon half size? that would be great!

**Comment by skinall13** [comment]
i have reduce the icon size o

**Comment by skinall13** [comment]
we have done this issue pls chek it ..
